apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sb-deploy
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: sb
  template: 
    metadata:
      labels:
        app: sb
    spec:
      containers:
      - name: ip-container
        image: 10.7.7.16:5000/sbimage:7
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: svc-sb
spec:
  selector:
    app: sb
  ports: 
    - name: sb-port
      protocol: TCP
      nodePort: 31000
      port: 8085
      targetPort: 8085

  type: NodePort
