apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myhttpd-deploy
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: myhttpd
  template: 
    metadata:
      labels:
        app: myhttpd
    spec:
      containers:
      - name: ip-container
        image: 10.7.7.16:5000/myhttpd:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-httpd
spec:
  selector:
    app: myhttpd
  ports: 
    - name: myhttpd-port
      protocol: TCP
      nodePort: 32000
      port: 80
      targetPort: 80

  type: NodePort
